spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acruent
    username: root
    password: 9603
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 2022
      
planapi:
  messages:
    PlanSavSucc: Plan Saved successfully
    PlanNotSave: Plan Not Saved
    PlanUpdateSucc: Plan Updated Successfully
    PlanNotUpdate: Plan Not Updated 
    PlanDeleteSucc: Plan Delete Successfully
    PlanNotDelete: Plan Not Deleted
    PlanStatusChangeSucc: Plan Status Change Succeefully
    PlanStatusChangeNotSucc: Plan status not chaged
    
